import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Muhammed Nazeem / n4ze3m.site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="intro">
        <h1 className="heading text-xl sm:text-3xl mt-10">
          Hey 👋, I'm  Nazeem.
        </h1>
        <p className="text-md text-gray-500 bg-blue mt-3">
          {
            `I'm a full stack developer with over ${new Date().getFullYear() - 2019} years of experience. Experienced with all stages of the development cycle for web and mobile applications.`
          }
        </p>
        <div className="mt-6">
          <h1 className="font-bold uppercase text-md sm:text-lg">
            Skills
          </h1>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-2 mt-4 mb-4" >
            <li className="text-gray-500"> Golang</li>
            <li className="text-gray-500"> JavaScript</li>
            <li className="text-gray-500"> TypeScript</li>
            <li className="text-gray-500"> Python</li>
            <li className="text-gray-500"> Dart</li>
            <li className="text-gray-500"> Solidity</li>
            <li className="text-gray-500"> PHP</li>
            <li className="text-gray-500"> Bash</li>
            <li className="text-gray-500"> HTML</li>
            <li className="text-gray-500"> C</li>
            <li className="text-gray-500"> C++</li>
            <li className="text-gray-500"> MySQL</li>
            <li className="text-gray-500"> Postgres</li>
            <li className="text-gray-500"> MongoDB</li>
            <li className="text-gray-500"> Docker</li>
            <li className="text-gray-500"> Kubernetes</li>
          </div>
          <span className="text-gray-400 mt-4"> and more...</span>
        </div>
      </main>
    </div>
  )
}
